openapi: "3.0.3"
info:
  version: "1.0.0"
  title: "carman public API"
  description: Configure Radar Charts

paths:
  /assessmentTemplates:
    get:
      summary: List all assessment templates
      responses:
        "200":
          $ref: "#/components/responses/AssessmentTemplates"

    post:
      summary: Create a new assessment template
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AssessmentTemplate"
      responses:
        "201":
          $ref: "#/components/responses/AssessmentTemplate"
  
  /assessmentTemplates/{templateID}:
    parameters:
      - name: templateID
        description: The unique identifier of the assessment template
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/ID"
    get:
      summary: Read an assessment template
      responses:
        "200":
          $ref: "#/components/responses/AssessmentTemplate"

    put:
      summary: Update an existing assessment template
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AssessmentTemplate"
      responses:
        "200":
          $ref: "#/components/responses/AssessmentTemplate"

  /charts/designs/radar/{designID}:
    parameters:
      - name: designID
        description: The unique identifier of the chart design
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/ID"
    get:
      summary: Read a Radar Chart Design
      responses:
        "200":
          $ref: "#/components/responses/RadarChartDesign"

    put:
      summary: Update an existing radar chart design
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RadarChartDesign"
      responses:
        "200":
          $ref: "#/components/responses/RadarChartDesign"

  /charts/designs/radar:
    get:
      summary: List all radar chart designs
      responses:
        "200":
          $ref: "#/components/responses/RadarChartDesigns"

    post:
      summary: Create a new radar chart design
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RadarChartDesign"
      responses:
        "201":
          $ref: "#/components/responses/RadarChartDesign"

components:
  schemas:
    AssessmentTemplate:
      description: A template for an assessment
      type: object
      required:
        - label
        - name
        - scales
      properties:
        id:
          $ref: "#/components/schemas/ID"
        label:
          type: string
          minLength: 5
          maxLength: 50
        name:
          type: string
          minLength: 5
          maxLength: 50
        scales:
          type: array
          uniqueItems: true
          items:
            $ref: "#/components/schemas/Scale"

    EdgeDesign:
      description: Design parameters for edges of a chart
      type: object
      required:
        - color
        - style
        - thickness
      properties:
        color:
          type: string
          pattern: "^#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$"
        style:
          type: string
          enum:
            - solid
            - dashed
        thickness:
          type: number
          format: int32
          minimum: 1

    ID:
      description: A unique identifier
      type: string
      pattern: /^[a-f\d]{24}$/

    RadarChartDesign:
      type: object
      required:
        - name
        - circularEdges
        - outerEdge
        - radialEdges
        - startingAngle
      properties:
        id:
          $ref: "#/components/schemas/ID"
        name:
          type: string
        circularEdges:
          $ref: "#/components/schemas/EdgeDesign"
        outerEdge:
          $ref: "#/components/schemas/EdgeDesign"
        radialEdges:
          $ref: "#/components/schemas/EdgeDesign"
        startingAngle:
          type: number

    Scale:
      description: A scale for a chart axis
      type: object
      required:
        - label
        - name
        - steps
      properties:
        id:
          $ref: "#/components/schemas/ID"
        label:
          type: string
          minLength: 5
          maxLength: 50
        name:
          type: string
          minLength: 5
          maxLength: 50
        steps:
          type: array
          uniqueItems: true
          items:
            type: object
            required:
              - label
              - value
            properties:
              label:
                type: string
                minLength: 1
                maxLength: 20
              value:
                type: number
                format: int32
                minimum: 0

    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string

  responses:
    AssessmentTemplate:
      description: An assessment template
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AssessmentTemplate"
            required: id

    AssessmentTemplates:
      description: A list of assessment templates
      content:
        application/json:
          schema:
            type: object
            required:
              - items
            properties:
              items:
                type: array
                items:
                  $ref: "#/components/schemas/AssessmentTemplate"
                  required: id

    RadarChartDesign:
      description: A radar chart design
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RadarChartDesign"
            required: id

    RadarChartDesigns:
      description: A list of radar chart designs
      content:
        application/json:
          schema:
            type: object
            required:
              - items
            properties:
              items:
                type: array
                items:
                  $ref: "#/components/schemas/RadarChartDesign"
                  required: id
